### ISSUE TITLE
[Parser] Update and fix parser issues

### ISSUE THREAD

**Issue by leMicin** [Sidekick-Poe/Sidekick#6]
# Introduction
This task encompasses some parser issues we had documented in our previous repository. We have grouped them in one issue here.

# Tasks
- [x] Make sure the Atzoatl temple maps are parsable and price checkable
- [x] Error parsing unidentified influenced item
```
Item Class: One Hand Maces
Rarity: Rare
Ornate Mace
--------
One Handed Mace
Physical Damage: 53-67
Critical Strike Chance: 5.00%
Attacks per Second: 1.20
Weapon Range: 11
--------
Requirements:
Strength: 161
--------
Sockets: R-R-R 
--------
Item Level: 76
--------
15% reduced Enemy Stun Threshold (implicit)
--------
Unidentified
--------
Hunter Item
```
- [x] Rare Blighted Map not detected as blighted
```
Item Class: Maps
Rarity: Rare
Nightmare Spires
Blighted Spider Forest Map
--------
Map Tier: 2
Atlas Region: Lex Proxima
Item Quantity: +55% (augmented)
Item Rarity: +32% (augmented)
Monster Pack Size: +21% (augmented)
--------
Item Level: 69
--------
Area is infested with Fungal Growths
Map's Item Quantity Modifiers also affect Blight Chest count at 20% value (implicit)
Natural inhabitants of this area have been removed (implicit)
--------
Monsters deal 54% extra Physical Damage as Lightning
Unique Boss has 25% increased Life
Unique Boss has 45% increased Area of Effect
Slaying Enemies close together has a 13% chance to attract monsters from Beyond
Players have 20% less Recovery Rate of Life and Energy Shield
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
```
- [x] Can't price check organs
```
Item Class: Metamorph Sample
Rarity: Unique
Portentia, the Foul's Heart
--------
Uses: Blood Bubble
--------
Item Level: 79
--------
Drops additional Rare Jewellery
Drops additional Currency Items
Drops additional Currency Items
Drops additional Rare Weapons
Drops additional Rare Armour
--------
Combine this with four other different samples in Tane's Laboratory.
```
- [x] Make sure the influences are still parsable
